apiVersion: apps/v1
kind: Deployment
metadata:
  name: swype-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swype-app
  template:
    metadata:
      labels:
        app: swype-app
    spec:
      containers:
        - name: stripe
          image: uonyeka/stripe:linux-amd64 # Use uonyeka/stripe:linux-arm64 if you are building locally on a Mac
          ports:
            - containerPort: 5003
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"  # Reduced from 1 to 250m
              memory: "500Mi"  # Reduced from 4Gi to 500Mi
            limits:
              cpu: "500m"  # Reduced from 1 to 500m
              memory: "1Gi"  # Reduced from 4Gi to 1Gi
